# Generated by Django 3.1.2 on 2020-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_box'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(to='accounts.Box'),
        ),
    ]
