# Generated by Django 3.1.2 on 2020-10-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201020_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='boxes',
        ),
    ]
