# Generated by Django 3.1.2 on 2020-11-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_box'),
        ('posts', '0003_auto_20201020_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='boxes',
            field=models.ManyToManyField(related_name='tags', to='accounts.Box'),
        ),
    ]
