# Generated by Django 3.1.2 on 2020-11-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201115_0346'),
        ('accounts', '0003_box'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box',
        ),
    ]
